services:
  - type: web
    name: floodpath-api
    env: python
    buildCommand: |
      # Install system dependencies
      echo "Installing system dependencies..."
      apt-get update
      apt-get install -y wget gnupg unzip xvfb libxi6 libgconf-2-4 curl lsb-release libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpango-1.0-0 libcairo2 libatspi2.0-0

      # Install Python dependencies
      echo "Installing Python dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt

      # Install Playwright and browsers with explicit paths
      echo "Installing Playwright browsers..."
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright
      python -m playwright install --with-deps chromium
      
      # Verify installation and browser path
      echo "Verifying Playwright installation..."
      python -m playwright --version
      ls -la /opt/render/.cache/ms-playwright/chromium-*/chrome-linux/chrome
      
      # Set permissions
      chmod -R 755 /opt/render/.cache/ms-playwright
    startCommand: |
      # Start Xvfb
      echo "Starting Xvfb..."
      Xvfb :99 -screen 0 1024x768x16 &
      
      # Verify Xvfb is running
      echo "Verifying Xvfb..."
      ps aux | grep Xvfb
      
      # Set environment variables for Playwright
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright
      export DISPLAY=:99
      
      # Start the application
      echo "Starting application..."
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENABLE_SSL
        value: true
      - key: RENDER
        value: true
      - key: DISPLAY
        value: :99
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 