services:
  - type: web
    name: floodpath-api
    env: python
    buildCommand: |
      # Install Chrome dependencies
      echo "Installing Chrome dependencies..."
      apt-get update
      apt-get install -y wget gnupg unzip xvfb libxi6 libgconf-2-4 curl lsb-release

      # Add Chrome repository
      echo "Setting up Chrome repository..."
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list

      # Install Chrome
      echo "Installing Chrome..."
      apt-get update
      apt-get install -y google-chrome-stable

      # Verify Chrome installation
      echo "Verifying Chrome installation..."
      google-chrome --version || echo "Chrome installation failed"
      which google-chrome || echo "Chrome binary not found in PATH"

      # Install ChromeDriver
      echo "Installing ChromeDriver..."
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
      echo "Chrome version: $CHROME_VERSION"
      
      # Download and install ChromeDriver
      wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
      CHROMEDRIVER_VERSION=$(cat "LATEST_RELEASE_$CHROME_VERSION")
      echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
      
      wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      # Verify ChromeDriver installation
      echo "Verifying ChromeDriver installation..."
      chromedriver --version || echo "ChromeDriver installation failed"
      which chromedriver || echo "ChromeDriver binary not found in PATH"

      # Install Python dependencies
      echo "Installing Python dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt

      # List installed packages
      echo "Installed packages:"
      dpkg -l | grep -E 'chrome|chromium'
    startCommand: |
      # Start Xvfb
      echo "Starting Xvfb..."
      Xvfb :99 -screen 0 1024x768x16 &
      
      # Verify Xvfb is running
      echo "Verifying Xvfb..."
      ps aux | grep Xvfb
      
      # Start the application
      echo "Starting application..."
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENABLE_SSL
        value: true
      - key: RENDER
        value: true
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: DISPLAY
        value: :99
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 