services:
  - type: web
    name: floodpath-api
    env: python
    buildCommand: |
      # Install system dependencies
      echo "Installing system dependencies..."
      apt-get update
      apt-get install -y wget gnupg unzip xvfb libxi6 libgconf-2-4 curl lsb-release

      # Install Python dependencies
      echo "Installing Python dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt

      # Install Playwright browsers
      echo "Installing Playwright browsers..."
      playwright install chromium
      playwright install-deps
    startCommand: |
      # Start Xvfb
      echo "Starting Xvfb..."
      Xvfb :99 -screen 0 1024x768x16 &
      
      # Verify Xvfb is running
      echo "Verifying Xvfb..."
      ps aux | grep Xvfb
      
      # Start the application
      echo "Starting application..."
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENABLE_SSL
        value: true
      - key: RENDER
        value: true
      - key: DISPLAY
        value: :99
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 