services:
  - type: web
    name: floodpath-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENABLE_SSL
        value: true
      - key: RENDER
        value: true
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: DISPLAY
        value: :99
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 